server:
  port: 8080
spring:
  application:
    name: 251210_thymeleaf
    #프로파일 활성화 (application-dev.yaml/yml)
  profiles:
    active: dev
  # DB 설정 (dev에서 활성화)
  #View Resolver & Template Engine
  thymeleaf:
    #prefix: classpath:/templates/
    #suffix: .html
    # default(기본값)으로 충분

    cache: false
